apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-java-app
  template:
    metadata:
      labels:
        app: simple-java-app
    spec:
      containers:
        - name: simple-java-app
          image: yalkarnawi19/simple-java-app:101
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
